# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1

notifications:
  email: false

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit
